global.playerItems = {
	5: 		{id: 5, description: "Вооружение сил внутренней безопасности. Калибр 9мм.", maxCount: 1, weight: 1},	
	7: 		{id: 7, description: "Нелетальный электрошок. Произведен для использования полицией.", maxCount: 1, weight: 1},
	8:		{id: 8, description: 'Винтажный пистолет',								maxCount: 1, weight: 2},
	9:		{id: 9, description: 'Бронебойный пистолет', 							maxCount: 1, weight: 1.5}, 
	12:		{id: 12, description: 'Тяжелый пистолет', 								maxCount: 1, weight: 2}, 
	17:		{id: 17, description: 'Пистолет-пулемет (микро)', 						maxCount: 1, weight: 2}, 
	19:		{id: 19, description: 'Пистолет-пулемет', 								maxCount: 1, weight: 2.5}, 
	23:		{id: 23, description: 'Штурмовой пистолет-пулемет',						maxCount: 1, weight: 3},
	24: 	{id: 24, description: "Вооружение сил внутренней безопасности. Пистолет-пулемёт калибра 9мм.", maxCount: 1, weight: 1},
	26: 	{id: 26, description: "Резиновая полицейская дубинка.", 				maxCount: 1, weight: 1},
	41: 	{id: 41, description: 'Помповый дробовик', 								maxCount: 1, weight: 3}, 
	43: 	{id: 43, description: 'Обрез', 											maxCount: 1, weight: 2.5}, 
	45: 	{id: 45, description: 'Штурмовой дробовик', 							maxCount: 1, weight: 4},
	60:		{id: 60, description: 'Особый карабин', 								maxCount: 1, weight: 4.5},
	62: 	{id: 62, description: 'Штурмовая винтовка', 							maxCount: 1, weight: 4},
	67: 	{id: 67, description: 'Автоматический карабин', 						maxCount: 1, weight: 4},
	68: 	{id: 68,																maxCount: 1, weight: 0.1}, 
	69: 	{id: 69,																maxCount: 1, weight: 0.1}, 
	71: 	{id: 71, description: "Емкость для переноса бензина.", 					maxCount: 1, weight: 3},
	72: 	{id: 72, description: "Восстанавливает 100 ед здоровья.", 				maxCount: 5, weight: 3.5},
	73: 	{id: 73, description: "Восстанавливает 40 ед. сытости.", 				maxCount: 5, weight: 0.5},
	74: 	{id: 74, description: "Восстанавливает 75 ед. жажды и 25 ед. сытости.", maxCount: 5, weight: 0.6},
	75: 	{id: 75, description: "Восстанавливает 50 ед сытости.", 				maxCount: 6, weight: 0.2},
	77:		{id: 77, description: "Восстанавливает 70 ед. сытости.",name: "Бургер",	maxCount: 5, weight: 0.8},
	78: 	{id: 78, description: "Восстанавливает 65 ед. сытости.",name: "Хот-дог",maxCount: 5, weight: 0.6},
	79: 	{id: 79, description: "Восстанавливает 50 ед. сытости.",				maxCount: 5, weight: 0.2},
	80:		{id: 80, description: "Восстанавливает 50 ед. жажды.", 					maxCount: 5, weight: 0.6},
	93: 	{id: 93, description: "Набор инструментов для починки машин.", 			maxCount: 1, weight: 6},
	95: 	{id: 95, description: "Восстанавливает 30 ед. сытости.", 				maxCount: 8, weight: 0.3},
	99: 	{id: 99, description: 'Патроны 9мм.', 									maxCount: 60, weight: 0.01}, 
	100: 	{id: 100, description: 'Патроны 12 калибр', 							maxCount: 20, weight: 0.05}, 
	102: 	{id: 102, description: 'Патроны 5.56', 									maxCount: 30, weight: 0.05},
	104: 	{id: 104, description: "Крепкий алкоголь, быстро вызывает опьянение.", 	maxCount: 5, weight: 0.5},
	105:	{id: 105, description: "Крепкий алкоголь, быстро вызывает опьянение. Короткая выдержка.", maxCount: 5, weight: 0.5},
	106:	{id: 106, description: "Дорогое и качественное шампанское.", 			maxCount: 5, weight: 0.75},
	107:	{id: 107, description: "Ликер средней крепости.", 						maxCount: 5, weight: 0.5},
	108:	{id: 108, description: "Апельсиновый ликер средней крепости.", 			maxCount: 5, weight: 0.5},
	109:	{id: 109, description: "Алкоголь средней крепости.", 					maxCount: 5, weight: 0.75},
	110:	{id: 110, description: "Вермут средней крепости.", 						maxCount: 5, weight: 0.75},
	111:	{id: 111, description: "Бренди пятилетней выдержки.", 					maxCount: 5, weight: 0.5},
	112:	{id: 112, description: "Очень крепкий алкоголь. Быстро вызывает опьянение. Содержит туйон.", maxCount: 5, weight: 0.5},
	113:	{id: 113, description: "Коньяк трехлетней выдержки.", 					maxCount: 5, weight: 0.5},
	114:	{id: 114, description: "Элитный алкоголь. Выдержка не менее 6 лет.", 	maxCount: 5, weight: 0.7},
	115:	{id: 115, description: "Крепкий алкоголь, быстро вызывает опьянение.", 	maxCount: 5, weight: 0.5},
	116:	{id: 116, description: "Куртка",										maxCount: 1},
	117:	{id: 117, description: "Очки",											maxCount: 1},
	118:	{id: 118, description: "Перчатки",										maxCount: 1},
	119:	{id: 119, description: "Шапка",											maxCount: 1},
	120:	{id: 120, description: "Штаны",											maxCount: 1},
	121:	{id: 121, description: "Кроссовки",										maxCount: 1},
	122:	{id: 122, description: "Футболка",										maxCount: 1}
}